export const GRID_ELEMENT_WIDTH = 60;

export const GRID_SIZES_SMALL = {
  GRID_HEIGHT: 5,
  GROUND_HEIGHT: 1,
  HERO_SIZE: 1,
  JUMP: 2,
};

export const GRID_SIZES_LARGE = {
  GRID_HEIGHT: 10,
  GROUND_HEIGHT: 2,
  HERO_SIZE: 3,
  JUMP: 3,
};

export const FORMATION_GRID_SIZES_SMALL = {
  GRID_HEIGHT: 11,
  GROUND_HEIGHT: 4,
  HERO_SIZE: 1,
  JUMP: 2,
  STUDENT_DESKS_HEIGHT: 3,
  STUDENT_DESKS_BOTTOM: 0.5,
};

export const FORMATION_GRID_SIZES_LARGE = {
  GRID_HEIGHT: 14,
  GROUND_HEIGHT: 6,
  HERO_SIZE: 3,
  JUMP: 3,
  STUDENT_DESKS_HEIGHT: 2,
  STUDENT_DESKS_BOTTOM: 3,
};
